# Generated by Django 5.0.2 on 2024-04-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
        ),
    ]
